### ISSUE TITLE
Donate to crc-org

### ISSUE THREAD

**Issue by albfan** [lilyLuLiu/crc-trigger#1]
this task wrapping is really helpful

What about move this into crc org as private?

CC @gbraad @adrianriobo

**Comment by adrianriobo** [comment]
I would suggest not to, at least until all pipeline specs can be publicly accessible

**Comment by albfan** [comment]
My suggestion is to donate as private, but let's reject by now

**Comment by adrianriobo** [comment]
In any case if it make sense to be shared to facilitate contributions we have now the https://github.com/devtools-qe-incubator may it will fit there for the moment and once it is mature enough we can think on moving it to crc-org

**Comment by gbraad** [comment]
I am pragmatic. I prefer things to be public when possible, and restricted when necessary. This I believe is to workaround a current limitation/issue with the testing farm? If so, we can wait... As it would also rely on the config on the end of TF to work.

Lu makes the call.

**Comment by lilyLuLiu** [comment]
I think these scripts should be placed in the same repo with the pipeline definition, which is qe-platform for now. As qe-platform will be migrated to public repo for Konflux, let's wait until the pipeline definition is settled.
